dist: xenial

language: python
python:
  - "2.6"
  - "2.7"
  - "3.5"

# before_install:

script:
  - pip install mwscan
  - mwscan --quiet --checksum --rules rules/magehost.yar --whitelist rules/magehost_whitelist.json .

notifications:
  email: true

deploy:
  provider: s3
  region: $AWS_DEFAULT_REGION
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: magehost-mwscan
  local_dir: rules
  acl: public_read
  skip_cleanup: true
  on:
    repo: magehost/magento-malware-scanner
