# Travis forced-updated to trusty somewhere in summer 2017, need to rebuild yara pkgs
dist: precise

language: python
python:
  - "2.6"
  - "2.7"
  - "3.5"

before_install:
  # requires precise
  - wget http://ubuntu.byte.nl/pool/hypernode/y/yara/yara_3.4.0+dfsg-2build1_amd64.deb
  - wget http://ubuntu.byte.nl/pool/hypernode/y/yara/libyara3_3.4.0+dfsg-2build1_amd64.deb
  - sudo dpkg -i *3.4.0*.deb

script:
  - pip install yara-python requests-cache mock
  - PYTHONPATH=mwscan nosetests -v mwscan/tests/test_mwscan.py
  - python tools/validate_signatures.py

  # This will only run under Py3 and when the rules have changed
  - bash tools/travis_test_magento_releases.sh

notifications:
  email: false